-- To run the HSQLDB Database tool:
-- java -cp <App install dir>/WEB-INF/lib/hsqldb.jar org.hsqldb.util.DatabaseManagerSwing
--
-- Driver settings:
--
-- Type: HSQLDB Database Engine Standalone
-- Driver: org.hsqldb.jdbcDriver
-- URL: jdbc:hsqldb:file:<file location. I use /opt/PingOne/Sample/db>
-- User: SA
-- Password: 2Federate
--
DROP TABLE Role IF EXISTS;
DROP TABLE USER IF EXISTS;
DROP TABLE Account IF EXISTS;
DROP TABLE Account_Domain IF EXISTS;
DROP TABLE User_Role IF EXISTS;
DROP TABLE User_Password IF EXISTS;
DROP TABLE User_Attribute IF EXISTS;
DROP TABLE Address IF EXISTS;

CREATE TABLE Role (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
name varchar(32),
description varchar(255),
PRIMARY KEY (id),
UNIQUE (name)
);

CREATE TABLE Address (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
name varchar(128),
street1 varchar(128),
street2 varchar(128),
city varchar(128),
region varchar(128),
country varchar(3),
postal varchar(12),
PRIMARY KEY (id),
);

CREATE TABLE Account (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
name varchar(128),
addressId INTEGER,
ssoEnabled BOOLEAN DEFAULT false,
ssoIdpId varchar(128),
PRIMARY KEY (id),
UNIQUE (name),
CONSTRAINT fk_account_address FOREIGN KEY (addressId) REFERENCES Address (id)
);

CREATE TABLE Account_Domain (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
accountId INTEGER,
domain varchar(128),
UNIQUE (domain)
);

CREATE TABLE User (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
firstName varchar(128),
lastName varchar(128),
email varchar(128),
accountId INTEGER,
addressId INTEGER,
PRIMARY KEY (id),
UNIQUE (email),
CONSTRAINT fk_user_account FOREIGN KEY (accountId) REFERENCES Account (id),
CONSTRAINT fk_user_address FOREIGN KEY (addressId) REFERENCES Address (id)
);

CREATE TABLE User_Password(
userId INTEGER,
password varchar(32),
UNIQUE (userId)
);

CREATE TABLE User_Role (
userId INTEGER,
roleId INTEGER,
PRIMARY KEY (userId,roleId)
);

CREATE TABLE User_Attribute (
id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
userId INTEGER,
attrKey varchar(128),
attrValue varchar(255),
PRIMARY KEY(id)
);

--
-- Add Roles
--
-- Id=1, name=super
INSERT INTO Role(name, description) VALUES('super', 'Super User. Limited to MyLittlePony employees');
-- Id=2, name=admin
INSERT INTO Role(name, description) VALUES('admin', 'Account administrator');
-- Id=3, name=user
INSERT INTO Role(name, description) VALUES('user', 'Account user');

--
-- Add Accounts
--

-- Id=1, MyLittlePony
INSERT INTO Account (name) VALUES ('mylittlepony.com');
-- Address Id=1
INSERT INTO Address (name, street1, street2,city,region,country,postal ) VALUES ('General','100 Wall St.','Suite 100', 'Gotham','NY','US','12345');
UPDATE Account SET addressId=1 WHERE id=1;
-- Domain
INSERT INTO Account_Domain(accountId, domain) VALUES(1, 'mylittlepony.com');

-- Id=2, Customer
INSERT INTO Account (name) VALUES ('Customer');
-- Address Id=2
INSERT INTO Address (name, street1, street2,city,region,country,postal ) VALUES ('General','2600 E. 52nd St.','Suite 270', 'Gotham','NY','US','12345');
UPDATE Account SET addressId=2 WHERE id=2;
-- Domain
INSERT INTO Account_Domain(accountId, domain) VALUES(2, 'customer.com');

--
-- Users
--

-- Id=1, dskyberg@mylittlepony.com
INSERT INTO User (firstName, lastName, email, accountId) VALUES ('David', 'Skyberg', 'dskyberg@mylittlepony.com', 1);
-- Password
INSERT INTO User_Password (userId, password) VALUES (1, '2Federate');
-- Roles
INSERT INTO User_Role (userId, roleId) VALUES (1, 1);
INSERT INTO User_Role (userId, roleId) VALUES (1, 2);
INSERT INTO User_Role (userId, roleId) VALUES (1, 3);

-- Id=1, joe@customer.com
INSERT INTO User (firstName, lastName, email, accountId) VALUES ('Joe', 'Test', 'joe@customer.com', 2);
-- Password
INSERT INTO User_Password (userId, password) VALUES (2, '2Federate');
-- Roles
INSERT INTO User_Role (userId, roleId) VALUES (2, 2);
INSERT INTO User_Role (userId, roleId) VALUES (2, 3);

-- Id=1, sue@customer.com
INSERT INTO User (firstName, lastName, email, accountId) VALUES ('Sue', 'Test', 'sue@customer.com', 2);
-- Password
INSERT INTO User_Password (userId, password) VALUES (3, '2Federate');
-- Roles
INSERT INTO User_Role (userId, roleId) VALUES (3, 3);

SELECT User.id as id, User.firstName as firstName,
User.lastName as lastName, User.email as email, User_Password.password as password,
Account.name as company
FROM User JOIN Account ON User.accountId=Account.id
JOIN User_Password ON User_Password.userId=User.id
WHERE email='dskyberg@mylittlepony.com';
